spring:
  application:
    name: query-example
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://bailian-aliyun-cdh2.bl-ai.com:15432/report_db
    username: postgres
    password: 123456

server:
  port: 10081